#
# Example Configuration for `SuiteConfigReader`
#
Name: "dataset_name"
OutputFolder: "../../out/dataset_name"
XmlFileLocation: "../../data/conformity/dataset_name"

DataSource:
  BaseUrl: "http://localhost:3030/dataset_name"
  Graphs:
    OP: "/op" # Target graph for MeasurementSimulation
    MEAS: "/meas" # Target graph for MeasurementSimulation
    SV: "/sv" # Target graph for SV-Profile Export
  CIM-Namespace: "http://iec.ch/TC57/CIM100#"

Steps:
  OwnFusekiContainer: false
  UploadXmlFiles: true
  MeasurementSimulation: true
  Stes: true

MeasurementSimulation:
  Ranges: "./meas_ranges.yaml"

Converter:
  onlyTopoIsland: false # convert only elements in a topological island
  # topoIslandName: "name" # convert only elements in a specific topological island
  sourcesFromSV: false # Add source from SV (cim:TopologicalIsland.AngleRefTopologicalNode)
  NetworkSplitting:
    Enable: false
    AddSources: false # Add sources instead of loads
    ## only following branches
    Branches:
      active: "cut1" # Select set of substations
      cut1: []
    ## only branches between substations in following list and the rest of the network
    Substations:
      active: "cut1" # Select set of substations
      cut1: []

Stes:
  PgmCalculationParameters:
    Threads: -1
    MaxIterations: 100
    ErrorTolerance: 1.e-6
  ## compute subnets separately instead of all of them together
  ComputeIslandsSeparately: false
  ## empty list to compute all subnets, or list of subnet names, e.g. `["subnet_1", "subnet_4"]`
  ComputeOnlySubnets: []
  ## after splitting subnets, reconnect branches consecutively and compute the growing network
  ReconnectBranches: false

Logging:
  Level: "INFO" #CRITICAL, ERROR, WARNING, INFO, DEBUG
  File: "dataset_name.log"
